### ISSUE TITLE
"wBlock.app" would like to access data from other apps.

### ISSUE THREAD

**Issue by dkmar** [0xCUB3/wBlock#27]
I'm getting this prompt every time I launch safari / web apps. Is there anything I can do to have it keep permissions? 
<img width="349" alt="Screenshot 2024-12-29 at 1 10 04 PM" src="https://github.com/user-attachments/assets/88c5db3f-f1da-49e9-b5f3-6b5288df727a" />

**Comment by dkmar** [comment]
Yep, that's an option. The issue might be related to [group names](https://mjtsai.com/blog/2024/09/11/group-container-names-in-sequoia/).
> So far I used “group.com.bluebanana-software.iyf”, which leads to a permission dialog each time the app is started. Now it needs to be “\<TeamID>.com.bluebanana-software.iyf”.

**Comment by 0xCUB3** [comment]
Yes this is what you have to do. But this issue will be fixed shortly. v0.2 will be released by the end of the week.

**Comment by rootbeerdan** [comment]
> Giving the app full disk access stops it.

But also, don't give a random javascript extension on GitHub complete access to your Mac. That safeguard exists for a reason.

**Comment by 0xCUB3** [comment]
> > Giving the app full disk access stops it.
> 
> 
> 
> But also, don't give a random javascript extension on GitHub complete access to your Mac. That safeguard exists for a reason.

I am sorry that this was an issue in v0.1. As a solo developer, it is hard to catch every single issue, especially in the first ever public beta release. The reason why this wasn't on my radar was because my Mac wasn't throwing me these warnings, since it knew the app was signed on a trusted account.

As I already established, I fixed this issue and the resolution will be reflected in the v0.2 release. Instead of writing directly to a file to update filter lists, I am using AppStorage and UserDefaults, which are airtight and don't require access to the full disk.

**Comment by ceylog** [comment]
> > > Giving the app full disk access stops it.
> > 
> > 
> > But also, don't give a random javascript extension on GitHub complete access to your Mac. That safeguard exists for a reason.
> 
> I am sorry that this was an issue in v0.1. As a solo developer, it is hard to catch every single issue, especially in the first ever public beta release. The reason why this wasn't on my radar was because my Mac wasn't throwing me these warnings, since it knew the app was signed on a trusted account.
> 
> As I already established, I fixed this issue and the resolution will be reflected in the v0.2 release. Instead of writing directly to a file to update filter lists, I am using AppStorage and UserDefaults, which are airtight and don't require access to the full disk.

come on!!!

**Comment by 0xCUB3** [comment]
If you would like to test the new version without this issue, I have a TestFlight running: https://testflight.apple.com/join/SVpptVb5

For some reason, notarization is taking forever, so the official release on the GitHub is delayed.

**Comment by dkmar** [comment]
Works and no access requests yet. It's perfect thank you!

**Comment by hpr1999** [comment]
Did I understand correctly that I should not have to give full access since January?
I just installed 2.1.0 last week and I'm still getting these requests regularly.

**Comment by 0xCUB3** [comment]
There were some issues introduced in recent macOS releases. While I investigate, I recommend switching to the App Store release which does not have this issue due to a different permission system.

**Comment by 0xCUB3** [comment]
Ah, I found the GitHub/Homebrew DMG signing path was still keeping the legacy `group.skula.wBlock` app-group entitlement alongside the TeamID-prefixed one. On newest macOS direct-distributed apps should not keep that unprovisioned `group.*` entitlement, and that matches the repeated access prompt you’re seeing.

Fixed on `main` in `7fa8b85bd211f8853b9c2a94c624f84b24352e5f`. The current 2.1.0 DMG is still affected, so this needs a rebuilt GitHub/Homebrew release, likely 2.1.1. Let me know if you still experience issues after.
